on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Generate files
      run: pub run build_runner build
    - name: Run tests
      run: pub run test
    - name: Run tests
      run: pub run test
